# Generated by Django 6.0.6 on 2026-06-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('git', 'Git Repository'), ('web', 'Web Page / Documentation')], default='git', max_length=10)),
                ('last_indexed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('chunks_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Knowledge Source',
                'verbose_name_plural': 'Knowledge Sources',
            },
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
